- name: add a application user
  ansible.builtin.user:
    name: roboshop

- name: Removing directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: creating directory
  ansible.builtin.file:
    path: /app
    state: directory
- name: download and extract frontend content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/${{ component }}.zip
    dest: /tmp/${component}.zip
    remote_src: yes
