- name : configuring nodejs repos
  ansible.builtin.shell: https://rpm.nodesource.com/setup_lts.x | bash

- name: install nodejs
  ansible.builtin.yum:
     name: nodejs
     state: installed

- name: app prerequisites
  ansible.builtin.import_tasks:
    file: app_presetup.yml




#echo -e "$color installing dependencies $nocolor"
#npm install &>>${log_file}

#systemd_setup