- name : configuring nodejs repos
  ansible.builtin.shell: https://rpm.nodesource.com/setup_lts.x | bash

- name: install nodejs
  ansible.builtin.yum:
     name: nodejs
     state: installed



#app_presetup

#echo -e "$color installing dependencies $nocolor"
#npm install &>>${log_file}

#systemd_setup